### ISSUE TITLE
Albany no longer building with spack on Anvil

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/spack#12]
@matthewhoffman and I are seeing the following when we build on Albany with Gnu and OpenMPI:

<details>
 <summary>Spack error message</summary>

```
==> Installing albany-develop-hflw55t6ascfv7jdjfitbyl3wcegai5o
==> No binary for albany-develop-hflw55t6ascfv7jdjfitbyl3wcegai5o found: installing from source
==> No patches needed for albany
==> albany: Executing phase: 'cmake'
==> albany: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

4 errors found in build log:
     354    [ 31%] Building CXX object src/CMakeFiles/albanyLib.dir/disc/stk/Al
            bany_IossSTKMeshStruct.cpp.o
     355    cd /lcrc/group/e3sm/ac.xylar/spack_temp/ac.xasay-davis/spack-stage/
            spack-stage-albany-develop-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack-b
            uild-hflw55t/src && /gpfs/fs1/software/centos7/spack-latest/opt/spa
            ck/linux-centos7-x86_64/gcc-8.2.0/openmpi-4.1.1-x5n4m36/bin/mpic++ 
            -DALBANY_STK_EXPR_EVAL -DalbanyLib_EXPORTS -I/lcrc/group/e3sm/ac.xy
            lar/spack_temp/ac.xasay-davis/spack-stage/spack-stage-albany-develo
            p-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack-build-hflw55t/src -I/lcrc/
            group/e3sm/ac.xylar/spack_temp/ac.xasay-davis/spack-stage/spack-sta
            ge-albany-develop-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack-src/src -I
            /lcrc/group/e3sm/ac.xylar/spack_temp/ac.xasay-davis/spack-stage/spa
            ck-stage-albany-develop-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack-src/
            src/evaluators -I/lcrc/group/e3sm/ac.xylar/spack_temp/ac.xasay-davi
            s/spack-stage/spack-stage-albany-develop-hflw55t6ascfv7jdjfitbyl3wc
            egai5o/spack-src/src/evaluators/bc -I/lcrc/group/e3sm/ac.xylar/spac
            k_temp/ac.xasay-davis/spack-stage/spack-stage-albany-develop-hflw55
            t6ascfv7jdjfitbyl3wcegai5o/spack-src/src/evaluators/gather -I/lcrc/
            group/e3sm/ac.xylar/spack_temp/ac.xasay-davis/spack-stage/spack-sta
            ge-albany-develop-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack-src/src/ev
            aluators/interpolation -I/lcrc/group/e3sm/ac.xylar/spack_temp/ac.xa
            say-davis/spack-stage/spack-stage-albany-develop-hflw55t6ascfv7jdjf
            itbyl3wcegai5o/spack-src/src/evaluators/response -I/lcrc/group/e3sm
            /ac.xylar/spack_temp/ac.xasay-davis/spack-stage/spack-stage-albany-
            develop-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack-src/src/evaluators/s
            catter -I/lcrc/group/e3sm/ac.xylar/spack_temp/ac.xasay-davis/spack-
            stage/spack-stage-albany-develop-hflw55t6ascfv7jdjfitbyl3wcegai5o/s
            pack-src/src/evaluators/state -I/lcrc/group/e3sm/ac.xylar/spack_tem
            p/ac.xasay-davis/spack-stage/spack-stage-albany-develop-hflw55t6asc
            fv7jdjfitbyl3wcegai5o/spack-src/src/evaluators/utility -I/lcrc/grou
            p/e3sm/ac.xylar/spack_temp/ac.xasay-davis/spack-stage/spack-stage-a
            lbany-develop-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack-src/src/proble
            ms -I/lcrc/group/e3sm/ac.xylar/spack_temp/ac.xasay-davis/spack-stag
            e/spack-stage-albany-develop-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack
            -src/src/responses -I/lcrc/group/e3sm/ac.xylar/spack_temp/ac.xasay-
            davis/spack-stage/spack-stage-albany-develop-hflw55t6ascfv7jdjfitby
            l3wcegai5o/spack-src/src/disc/stk -I/lcrc/group/e3sm/ac.xylar/spack
            _temp/ac.xasay-davis/spack-stage/spack-stage-albany-develop-hflw55t
            6ascfv7jdjfitbyl3wcegai5o/spack-src/src/disc -I/lcrc/group/e3sm/ac.
            xylar/spack_temp/ac.xasay-davis/spack-stage/spack-stage-albany-deve
            lop-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack-src/src/utility -isystem
             /lcrc/group/e3sm/ac.xylar/spack_test/spack_for_mache_1.12.0/opt/sp
            ack/linux-centos7-sandybridge/gcc-8.2.0/trilinos-for-albany-develop
            -geu2ne7m7fvplmdn5s7r3gzraclf6d7t/include -isystem /lcrc/group/e3sm
            /ac.xylar/spack_test/spack_for_mache_1.12.0/opt/spack/linux-centos7
            -sandybridge/gcc-8.2.0/boost-1.80.0-i6guysn34mbdsncduqpgir432rtxrnq
            k/include -isystem /lcrc/group/e3sm/ac.xylar/spack_test/spack_for_m
            ache_1.12.0/opt/spack/linux-centos7-sandybridge/gcc-8.2.0/metis-5.1
            .0-xomfdtvdxfc2efzs2wn6sr74e5ccg7ps/include -isystem /gpfs/fs1/soft
            ware/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-8.2.0/
            hdf5-1.10.7-w35u23y/include -isystem /lcrc/group/e3sm/ac.xylar/spac
            k_test/spack_for_mache_1.12.0/opt/spack/linux-centos7-sandybridge/g
            cc-8.2.0/parmetis-4.0.3-lxu66szm7wjhi7djn2is4gabcbebkvpv/include -i
            system /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-cent
            os7-x86_64/gcc-8.2.0/netcdf-c-4.4.1-mtfptpl/include -isystem /gpfs/
            fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gc
            c-8.2.0/parallel-netcdf-1.11.0-a7ohxsg/include -O3 -DNDEBUG -fPIC -
            std=c++17 -MD -MT src/CMakeFiles/albanyLib.dir/disc/stk/Albany_Ioss
            STKMeshStruct.cpp.o -MF CMakeFiles/albanyLib.dir/disc/stk/Albany_Io
            ssSTKMeshStruct.cpp.o.d -o CMakeFiles/albanyLib.dir/disc/stk/Albany
            _IossSTKMeshStruct.cpp.o -c /lcrc/group/e3sm/ac.xylar/spack_temp/ac
            .xasay-davis/spack-stage/spack-stage-albany-develop-hflw55t6ascfv7j
            djfitbyl3wcegai5o/spack-src/src/disc/stk/Albany_IossSTKMeshStruct.c
            pp
     356    [ 32%] Building CXX object src/CMakeFiles/albanyLib.dir/disc/stk/Al
            bany_MultiSTKFieldContainer.cpp.o
     357    cd /lcrc/group/e3sm/ac.xylar/spack_temp/ac.xasay-davis/spack-stage/
            spack-stage-albany-develop-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack-b
            uild-hflw55t/src && /gpfs/fs1/software/centos7/spack-latest/opt/spa
            ck/linux-centos7-x86_64/gcc-8.2.0/openmpi-4.1.1-x5n4m36/bin/mpic++ 
            -DALBANY_STK_EXPR_EVAL -DalbanyLib_EXPORTS -I/lcrc/group/e3sm/ac.xy
            lar/spack_temp/ac.xasay-davis/spack-stage/spack-stage-albany-develo
            p-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack-build-hflw55t/src -I/lcrc/
            group/e3sm/ac.xylar/spack_temp/ac.xasay-davis/spack-stage/spack-sta
            ge-albany-develop-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack-src/src -I
            /lcrc/group/e3sm/ac.xylar/spack_temp/ac.xasay-davis/spack-stage/spa
            ck-stage-albany-develop-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack-src/
            src/evaluators -I/lcrc/group/e3sm/ac.xylar/spack_temp/ac.xasay-davi
            s/spack-stage/spack-stage-albany-develop-hflw55t6ascfv7jdjfitbyl3wc
            egai5o/spack-src/src/evaluators/bc -I/lcrc/group/e3sm/ac.xylar/spac
            k_temp/ac.xasay-davis/spack-stage/spack-stage-albany-develop-hflw55
            t6ascfv7jdjfitbyl3wcegai5o/spack-src/src/evaluators/gather -I/lcrc/
            group/e3sm/ac.xylar/spack_temp/ac.xasay-davis/spack-stage/spack-sta
            ge-albany-develop-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack-src/src/ev
            aluators/interpolation -I/lcrc/group/e3sm/ac.xylar/spack_temp/ac.xa
            say-davis/spack-stage/spack-stage-albany-develop-hflw55t6ascfv7jdjf
            itbyl3wcegai5o/spack-src/src/evaluators/response -I/lcrc/group/e3sm
            /ac.xylar/spack_temp/ac.xasay-davis/spack-stage/spack-stage-albany-
            develop-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack-src/src/evaluators/s
            catter -I/lcrc/group/e3sm/ac.xylar/spack_temp/ac.xasay-davis/spack-
            stage/spack-stage-albany-develop-hflw55t6ascfv7jdjfitbyl3wcegai5o/s
            pack-src/src/evaluators/state -I/lcrc/group/e3sm/ac.xylar/spack_tem
            p/ac.xasay-davis/spack-stage/spack-stage-albany-develop-hflw55t6asc
            fv7jdjfitbyl3wcegai5o/spack-src/src/evaluators/utility -I/lcrc/grou
            p/e3sm/ac.xylar/spack_temp/ac.xasay-davis/spack-stage/spack-stage-a
            lbany-develop-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack-src/src/proble
            ms -I/lcrc/group/e3sm/ac.xylar/spack_temp/ac.xasay-davis/spack-stag
            e/spack-stage-albany-develop-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack
            -src/src/responses -I/lcrc/group/e3sm/ac.xylar/spack_temp/ac.xasay-
            davis/spack-stage/spack-stage-albany-develop-hflw55t6ascfv7jdjfitby
            l3wcegai5o/spack-src/src/disc/stk -I/lcrc/group/e3sm/ac.xylar/spack
            _temp/ac.xasay-davis/spack-stage/spack-stage-albany-develop-hflw55t
            6ascfv7jdjfitbyl3wcegai5o/spack-src/src/disc -I/lcrc/group/e3sm/ac.
            xylar/spack_temp/ac.xasay-davis/spack-stage/spack-stage-albany-deve
            lop-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack-src/src/utility -isystem
             /lcrc/group/e3sm/ac.xylar/spack_test/spack_for_mache_1.12.0/opt/sp
            ack/linux-centos7-sandybridge/gcc-8.2.0/trilinos-for-albany-develop
            -geu2ne7m7fvplmdn5s7r3gzraclf6d7t/include -isystem /lcrc/group/e3sm
            /ac.xylar/spack_test/spack_for_mache_1.12.0/opt/spack/linux-centos7
            -sandybridge/gcc-8.2.0/boost-1.80.0-i6guysn34mbdsncduqpgir432rtxrnq
            k/include -isystem /lcrc/group/e3sm/ac.xylar/spack_test/spack_for_m
            ache_1.12.0/opt/spack/linux-centos7-sandybridge/gcc-8.2.0/metis-5.1
            .0-xomfdtvdxfc2efzs2wn6sr74e5ccg7ps/include -isystem /gpfs/fs1/soft
            ware/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-8.2.0/
            hdf5-1.10.7-w35u23y/include -isystem /lcrc/group/e3sm/ac.xylar/spac
            k_test/spack_for_mache_1.12.0/opt/spack/linux-centos7-sandybridge/g
            cc-8.2.0/parmetis-4.0.3-lxu66szm7wjhi7djn2is4gabcbebkvpv/include -i
            system /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-cent
            os7-x86_64/gcc-8.2.0/netcdf-c-4.4.1-mtfptpl/include -isystem /gpfs/
            fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gc
            c-8.2.0/parallel-netcdf-1.11.0-a7ohxsg/include -O3 -DNDEBUG -fPIC -
            std=c++17 -MD -MT src/CMakeFiles/albanyLib.dir/disc/stk/Albany_Mult
            iSTKFieldContainer.cpp.o -MF CMakeFiles/albanyLib.dir/disc/stk/Alba
            ny_MultiSTKFieldContainer.cpp.o.d -o CMakeFiles/albanyLib.dir/disc/
            stk/Albany_MultiSTKFieldContainer.cpp.o -c /lcrc/group/e3sm/ac.xyla
            r/spack_temp/ac.xasay-davis/spack-stage/spack-stage-albany-develop-
            hflw55t6ascfv7jdjfitbyl3wcegai5o/spack-src/src/disc/stk/Albany_Mult
            iSTKFieldContainer.cpp
     358    /lcrc/group/e3sm/ac.xylar/spack_temp/ac.xasay-davis/spack-stage/spa
            ck-stage-albany-develop-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack-src/
            src/disc/stk/Albany_ExtrudedSTKMeshStruct.cpp: In instantiation of 
            'Albany::ExtrudedSTKMeshStruct::extrudeBasalFields(const std::vecto
            r<stk::mesh::Entity>&, const std::vector<stk::mesh::Entity>&, GO, G
            O)::<lambda(const auto:6&, const auto:7&)> [with auto:6 = stk::mesh
            ::Field<double>*; auto:7 = stk::mesh::Field<double>*]':
     359    /lcrc/group/e3sm/ac.xylar/spack_temp/ac.xasay-davis/spack-stage/spa
            ck-stage-albany-develop-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack-src/
            src/disc/stk/Albany_ExtrudedSTKMeshStruct.cpp:1075:33:   required f
            rom here
  >> 360    /lcrc/group/e3sm/ac.xylar/spack_temp/ac.xasay-davis/spack-stage/spa
            ck-stage-albany-develop-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack-src/
            src/disc/stk/Albany_ExtrudedSTKMeshStruct.cpp:1057:36: internal com
            piler error: in tsubst_copy, at cp/pt.c:15478
     361               int node3dId = Ordering==COLUMN ? node2dId*(numLayers+1)
            +il+1 : il*maxGlobalNodes2dId+node2dId + 1;
     362                                        ^~~~~~
     363    [ 32%] Building CXX object src/CMakeFiles/albanyLib.dir/disc/stk/Al
            bany_OrdinarySTKFieldContainer.cpp.o
     364    cd /lcrc/group/e3sm/ac.xylar/spack_temp/ac.xasay-davis/spack-stage/
            spack-stage-albany-develop-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack-b
            uild-hflw55t/src && /gpfs/fs1/software/centos7/spack-latest/opt/spa
            ck/linux-centos7-x86_64/gcc-8.2.0/openmpi-4.1.1-x5n4m36/bin/mpic++ 
            -DALBANY_STK_EXPR_EVAL -DalbanyLib_EXPORTS -I/lcrc/group/e3sm/ac.xy
            lar/spack_temp/ac.xasay-davis/spack-stage/spack-stage-albany-develo
            p-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack-build-hflw55t/src -I/lcrc/
            group/e3sm/ac.xylar/spack_temp/ac.xasay-davis/spack-stage/spack-sta
            ge-albany-develop-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack-src/src -I
            /lcrc/group/e3sm/ac.xylar/spack_temp/ac.xasay-davis/spack-stage/spa
            ck-stage-albany-develop-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack-src/
            src/evaluators -I/lcrc/group/e3sm/ac.xylar/spack_temp/ac.xasay-davi
            s/spack-stage/spack-stage-albany-develop-hflw55t6ascfv7jdjfitbyl3wc
            egai5o/spack-src/src/evaluators/bc -I/lcrc/group/e3sm/ac.xylar/spac
            k_temp/ac.xasay-davis/spack-stage/spack-stage-albany-develop-hflw55
            t6ascfv7jdjfitbyl3wcegai5o/spack-src/src/evaluators/gather -I/lcrc/
            group/e3sm/ac.xylar/spack_temp/ac.xasay-davis/spack-stage/spack-sta
            ge-albany-develop-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack-src/src/ev
            aluators/interpolation -I/lcrc/group/e3sm/ac.xylar/spack_temp/ac.xa
            say-davis/spack-stage/spack-stage-albany-develop-hflw55t6ascfv7jdjf
            itbyl3wcegai5o/spack-src/src/evaluators/response -I/lcrc/group/e3sm
            /ac.xylar/spack_temp/ac.xasay-davis/spack-stage/spack-stage-albany-
            develop-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack-src/src/evaluators/s
            catter -I/lcrc/group/e3sm/ac.xylar/spack_temp/ac.xasay-davis/spack-
            stage/spack-stage-albany-develop-hflw55t6ascfv7jdjfitbyl3wcegai5o/s
            pack-src/src/evaluators/state -I/lcrc/group/e3sm/ac.xylar/spack_tem
            p/ac.xasay-davis/spack-stage/spack-stage-albany-develop-hflw55t6asc
            fv7jdjfitbyl3wcegai5o/spack-src/src/evaluators/utility -I/lcrc/grou
            p/e3sm/ac.xylar/spack_temp/ac.xasay-davis/spack-stage/spack-stage-a
            lbany-develop-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack-src/src/proble
            ms -I/lcrc/group/e3sm/ac.xylar/spack_temp/ac.xasay-davis/spack-stag
            e/spack-stage-albany-develop-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack
            -src/src/responses -I/lcrc/group/e3sm/ac.xylar/spack_temp/ac.xasay-
            davis/spack-stage/spack-stage-albany-develop-hflw55t6ascfv7jdjfitby
            l3wcegai5o/spack-src/src/disc/stk -I/lcrc/group/e3sm/ac.xylar/spack
            _temp/ac.xasay-davis/spack-stage/spack-stage-albany-develop-hflw55t
            6ascfv7jdjfitbyl3wcegai5o/spack-src/src/disc -I/lcrc/group/e3sm/ac.
            xylar/spack_temp/ac.xasay-davis/spack-stage/spack-stage-albany-deve
            lop-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack-src/src/utility -isystem
             /lcrc/group/e3sm/ac.xylar/spack_test/spack_for_mache_1.12.0/opt/sp
            ack/linux-centos7-sandybridge/gcc-8.2.0/trilinos-for-albany-develop
            -geu2ne7m7fvplmdn5s7r3gzraclf6d7t/include -isystem /lcrc/group/e3sm
            /ac.xylar/spack_test/spack_for_mache_1.12.0/opt/spack/linux-centos7
            -sandybridge/gcc-8.2.0/boost-1.80.0-i6guysn34mbdsncduqpgir432rtxrnq
            k/include -isystem /lcrc/group/e3sm/ac.xylar/spack_test/spack_for_m
            ache_1.12.0/opt/spack/linux-centos7-sandybridge/gcc-8.2.0/metis-5.1
            .0-xomfdtvdxfc2efzs2wn6sr74e5ccg7ps/include -isystem /gpfs/fs1/soft
            ware/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-8.2.0/
            hdf5-1.10.7-w35u23y/include -isystem /lcrc/group/e3sm/ac.xylar/spac
            k_test/spack_for_mache_1.12.0/opt/spack/linux-centos7-sandybridge/g
            cc-8.2.0/parmetis-4.0.3-lxu66szm7wjhi7djn2is4gabcbebkvpv/include -i
            system /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-cent
            os7-x86_64/gcc-8.2.0/netcdf-c-4.4.1-mtfptpl/include -isystem /gpfs/
            fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gc
            c-8.2.0/parallel-netcdf-1.11.0-a7ohxsg/include -O3 -DNDEBUG -fPIC -
            std=c++17 -MD -MT src/CMakeFiles/albanyLib.dir/disc/stk/Albany_Ordi
            narySTKFieldContainer.cpp.o -MF CMakeFiles/albanyLib.dir/disc/stk/A
            lbany_OrdinarySTKFieldContainer.cpp.o.d -o CMakeFiles/albanyLib.dir
            /disc/stk/Albany_OrdinarySTKFieldContainer.cpp.o -c /lcrc/group/e3s
            m/ac.xylar/spack_temp/ac.xasay-davis/spack-stage/spack-stage-albany
            -develop-hflw55t6ascfv7jdjfitbyl3wcegai5o/spack-src/src/disc/stk/Al
            bany_OrdinarySTKFieldContainer.cpp
     365    0x5962ac tsubst_copy
     366    	/blues/gpfs/software/centos7/spack-latest/var/spack/stage/gcc-8.2.
            0-xhxgy33yu3xpdtjpcw3f4g7wck2ptv7s/gcc-8.2.0/gcc/cp/pt.c:15476

     ...

     403    0x6bc878 instantiate_decl(tree_node*, bool, bool)
     404    	/blues/gpfs/software/centos7/spack-latest/var/spack/stage/gcc-8.2.
            0-xhxgy33yu3xpdtjpcw3f4g7wck2ptv7s/gcc-8.2.0/gcc/cp/pt.c:24053
     405    Please submit a full bug report,
     406    with preprocessed source if appropriate.
     407    Please include the complete backtrace with any bug report.
     408    See <https://gcc.gnu.org/bugs/> for instructions.
  >> 409    make[2]: *** [src/CMakeFiles/albanyLib.dir/disc/stk/Albany_Extruded
            STKMeshStruct.cpp.o] Error 1
     410    make[2]: *** Waiting for unfinished jobs....
     411    make[2]: Leaving directory `/lcrc/group/e3sm/ac.xylar/spack_temp/ac
            .xasay-davis/spack-stage/spack-stage-albany-develop-hflw55t6ascfv7j
            djfitbyl3wcegai5o/spack-build-hflw55t'
  >> 412    make[1]: *** [src/CMakeFiles/albanyLib.dir/all] Error 2
     413    make[1]: Leaving directory `/lcrc/group/e3sm/ac.xylar/spack_temp/ac
            .xasay-davis/spack-stage/spack-stage-albany-develop-hflw55t6ascfv7j
            djfitbyl3wcegai5o/spack-build-hflw55t'
  >> 414    make: *** [all] Error 2
```

</details>

The change seems to be somewhat recent -- thing worked as of January 12th.

Here is what I ran:
<details>
 <summary>Bash script</summary>

```bash
#!/bin/bash

module purge
module load cmake/3.20.3-vedypwm
module load perl/5.30.3-co3kopi
module load gcc/8.2.0-xhxgy33
module load openmpi/4.1.1-x5n4m36
module load intel-mkl/2020.4.304-d6zw4xa
module load hdf5/1.10.7-w35u23y
module load netcdf-c/4.4.1-mtfptpl
module load netcdf-fortran/4.4.4-5yd6dos
module load parallel-netcdf/1.11.0-a7ohxsg
export TMPDIR=/lcrc/group/e3sm/ac.xylar/spack_temp

set -e

if [ -d /lcrc/group/e3sm/ac.xylar/spack_test/spack_for_mache_1.12.0 ]; then
  cd /lcrc/group/e3sm/ac.xylar/spack_test/spack_for_mache_1.12.0
  git fetch origin
  git reset --hard origin/spack_for_mache_1.12.0
else
  git clone -b spack_for_mache_1.12.0 git@github.com:E3SM-Project/spack.git /lcrc/group/e3sm/ac.xylar/spack_test/spack_for_mache_1.12.0
  cd /lcrc/group/e3sm/ac.xylar/spack_test/spack_for_mache_1.12.0
fi
source share/spack/setup-env.sh



spack env remove -y dev_compass_1_2_0-alpha_4_gnu_openmpi_albany >& /dev/null && \
  echo "recreating environment: dev_compass_1_2_0-alpha_4_gnu_openmpi_albany" || \
  echo "creating new environment: dev_compass_1_2_0-alpha_4_gnu_openmpi_albany"
spack env create dev_compass_1_2_0-alpha_4_gnu_openmpi_albany /gpfs/fs1/home/ac.xylar/mpas-work/compass/simplify_local_mache/conda/build_anvil_gnu_openmpi_albany/dev_compass_1_2_0-alpha_4_gnu_openmpi_albany.yaml
spack env activate dev_compass_1_2_0-alpha_4_gnu_openmpi_albany
```
</details>

Here is the yaml file:
<details>
 <summary>dev_compass_1_2_0-alpha_4_gnu_openmpi_albany.yaml</summary>

```yaml
spack:
  specs:
  - cmake
  - gcc
  - openmpi

  - intel-mkl


  - hdf5
  - netcdf-c
  - netcdf-fortran
  - parallel-netcdf

  - esmf@8.2.0+mpi+netcdf~pio+pnetcdf
  - scorpio@1.3.2+pnetcdf~timing+internal-timing~tools+malloc
  - albany@develop+mpas

  concretizer:
    unify: true
  packages:
    all:
      compiler: [gcc@8.2.0]
      providers:
        mpi: [openmpi@4.1.1]

        lapack: [intel-mkl@2020.4.304]

    bison:
      externals:
      - spec: bison@3.0.4
        prefix: /usr
      buildable: false
    bzip2:
      externals:
      - spec: bzip2@1.0.6
        prefix: /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-6.5.0/bzip2-1.0.6-mbwr6sk
      buildable: false
    curl:
      externals:
      - spec: curl@7.72.0
        prefix: /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-6.5.0/curl-7.72.0-bnppi6e
      buildable: false
    diffutils:
      externals:
      - spec: diffutils@3.7
        prefix: /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-6.5.0/diffutils-3.7-lmwmgqg
      buildable: false
    findutils:
      externals:
      - spec: findutils@4.6.0
        prefix: /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-6.5.0/findutils-4.6.0-ef3lzvf
      buildable: false
    gettext:
      externals:
      - spec: gettext@0.19.8.1
        prefix: /usr
      buildable: false
    libiconv:
      externals:
      - spec: libiconv@1.16
        prefix: /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/intel-20.0.4/libiconv-1.16-gcutq6m
      buildable: false
    libxml2:
      externals:
      - spec: libxml2@2.9.10
        prefix: /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/intel-20.0.4/libxml2-2.9.10-dwvqy3m
      buildable: false
    m4:
      externals:
      - spec: m4@1.4.16
        prefix: /usr
      buildable: false
    openssl:
      externals:
      - spec: openssl@1.0.2k
        prefix: /usr
      buildable: false
    tar:
      externals:
      - spec: tar@1.26
        prefix: /usr
      buildable: false
    xz:
      externals:
      - spec: xz@5.2.5
        prefix: /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/intel-20.0.4/xz-5.2.5-6uopvxd
      buildable: false
    zlib:
      externals:
      - spec: zlib@1.2.11
        prefix: /gpfs/fs1/soft/chrysalis/spack/opt/spack/linux-centos8-x86_64/intel-20.0.4/zlib-1.2.11-dudhhig
      buildable: false
    cmake:
      externals:
      - spec: cmake@3.20.3
        prefix: /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-6.5.0/cmake-3.20.3-vedypwm
        modules:
        - cmake/3.20.3-vedypwm
      buildable: false
    perl:
      externals:
      - spec: perl@5.30.3
        prefix: /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-6.5.0/perl-5.30.3-co3kopi
        modules:
          - perl/5.30.3-co3kopi
      buildable: false
    gcc:
      externals:
      - spec: gcc@8.2.0
        prefix: /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-6.5.0/gcc-8.2.0-xhxgy33
        modules:
        - gcc/8.2.0-xhxgy33
      buildable: false
    openmpi:
      externals:
      - spec: openmpi@4.1.1
        prefix: /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-8.2.0/openmpi-4.1.1-x5n4m36
        modules:
        - openmpi/4.1.1-x5n4m36
      buildable: false
    intel-mkl:
      externals:
      - spec: intel-mkl@2020.4.304
        prefix: /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-8.2.0/intel-mkl-2020.4.304-d6zw4xa
        modules:
        - intel-mkl/2020.4.304-d6zw4xa
      buildable: false

    hdf5:
      externals:
      - spec: hdf5@1.10.7+cxx+fortran+hl+mpi
        prefix: /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-8.2.0/hdf5-1.10.7-w35u23y
        modules:
        - hdf5/1.10.7-w35u23y
      buildable: false
    netcdf-c:
      externals:
      - spec: netcdf-c@4.4.1+mpi~parallel-netcdf
        prefix: /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-8.2.0/netcdf-c-4.4.1-mtfptpl
        modules:
        - netcdf-c/4.4.1-mtfptpl
      buildable: false
    netcdf-fortran:
      externals:
      - spec: netcdf-fortran@4.4.4
        prefix: /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-8.2.0/netcdf-fortran-4.4.4-5yd6dos
        modules:
        - netcdf-fortran/4.4.4-5yd6dos
      buildable: false
    parallel-netcdf:
      externals:
      - spec: parallel-netcdf@1.11.0+cxx+fortran
        prefix: /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-8.2.0/parallel-netcdf-1.11.0-a7ohxsg
        modules:
        - parallel-netcdf/1.11.0-a7ohxsg
      buildable: false

  config:
    install_missing_compilers: false
  compilers:
  - compiler:
      spec: gcc@8.2.0
      paths:
        cc: /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-6.5.0/gcc-8.2.0-xhxgy33/bin/gcc
        cxx: /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-6.5.0/gcc-8.2.0-xhxgy33/bin/g++
        f77: /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-6.5.0/gcc-8.2.0-xhxgy33/bin/gfortran
        fc: /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-6.5.0/gcc-8.2.0-xhxgy33/bin/gfortran
      flags: {}
      operating_system: centos7
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
```

</details>
